### PR TITLE
Add serde support

### PR DESCRIPTION
**Pull request by ocboogie**

### CODE REVIEW

**Comment by Schlechtwetterfront** [comment]
What is the use case that makes you need serialization of those structs? I'm not against these changes, just curious.

I guess you ran the code through the auto formatter for the formatting changes?

**Comment by ocboogie** [comment]
I'm using this for a JSON-RPC

**Comment by ocboogie** [comment]
Oh wait I didn't mean to format the code. I can change that back if you would like

**Comment by Schlechtwetterfront** [comment]
No that's fine, it should have been formatted in the first place.

I guess what you're working on is not open to the public?

**Pull request merged**
